/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "var(--text-primary)",
        'on-primary': "var(--bg-primary)",
        ink: "var(--text-primary)",
        'ink-deep': "var(--text-primary-deep)",
        charcoal: "var(--text-primary)",
        body: "var(--text-secondary)",
        mute: "var(--text-tertiary)",
        stone: "var(--text-tertiary)",
        ash: "var(--text-tertiary)",
        canvas: "var(--bg-primary)",
        'surface-soft': "var(--bg-tertiary)",
        'surface-card': "var(--card-bg)",
        'surface-dark': "var(--bg-secondary)",
        'surface-dark-elevated': "var(--card-bg-elevated)",
        hairline: "var(--border)",
        'hairline-strong': "var(--border-strong)",
        'on-dark': "var(--bg-primary)",
        'on-dark-mute': "var(--text-tertiary)",
        accent: "var(--action-primary)",
        'accent-hover': "var(--action-hover)",
        'accent-active': "var(--action-active)",
        warning: "#ffb020",
        'warning-hover': "#e09400",
        'warning-active': "#c27d00",
        danger: "#fa4b4b",
        'danger-hover': "#d93838",
        'danger-active': "#b82a2a",
        success: "#2ed573",
      },
      fontFamily: {
        mono: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
        sans: ['"Plus Jakarta Sans"', 'ui-sans-serif', 'sans-serif'],
        display: ['"Playfair Display"', 'Georgia', 'serif'],
      },
      fontSize: {
        'display-xl': ['38px', { lineHeight: '1.5', fontWeight: '700' }],
        'heading-md': ['16px', { lineHeight: '1.5', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-strong': ['16px', { lineHeight: '1.5', fontWeight: '500' }],
        'body-tight': ['16px', { lineHeight: '1', fontWeight: '500' }],
        'link-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'button-md': ['16px', { lineHeight: '2', fontWeight: '500' }],
        'caption-md': ['14px', { lineHeight: '2', fontWeight: '400' }],
      },
      borderRadius: {
        'none': '0px',
        'sm': '4px',
        'full': '9999px',
      },
      spacing: {
        'xxs': '1px',
        'xs': '4px',
        'sm': '8px',
        'md': '12px',
        'lg': '16px',
        'xl': '24px',
        'xxl': '32px',
        'section': '96px',
      }
    },
  },
  plugins: [],
}
